#!/usr/bin/env bash
set -eEu -o pipefail
script_path="${BASH_SOURCE[0]}"
script_dir="$(cd "$(dirname "$script_path")" && pwd)"

AOC_ROOT="$script_dir"
AOC_USERNAME='AOC_USERNAME_NOT_SET'

day_sortable() {
    day=$1
    prefix=$([ "$day" -lt "10" ] && echo "0" || echo "")
    echo "day${prefix}${day}"
}

example_dir() {
    day=$1
    year=$2
    echo "example-files/$year/$(day_sortable $day)"
}

solution_dir() {
    year=$1
    if [ "$AOC_USERNAME" == "AOC_USERNAME_NOT_SET" ]
    then
        echo "solution-files/$year"
    else
        # Support shared repo with friends
        echo "solution-files-$AOC_USERNAME/$year"
    fi
}

question_dir() {
    day=$1
    year=$2
    echo "question-files/$year/$(day_sortable $day)"
}

question_file() {
    day=$1
    year=$2
    question_name=$3
    echo "$(question_dir $day $year)/$question_name.question"
}

if [ -f "$script_path.overrides" ]
then
    source "$script_path.overrides"
fi
